src/Entity/FamilyMember.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FamilyMemberRepository")
 */
class FamilyMember
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Color;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $AvailableTime;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Activity", mappedBy="FamilyMember_Activity")
     */
    private $activities;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="familymember")
     */
    private $user;

    public function __construct()
    {
        $this->activities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getType(): ?bool
    {
        return $this->Type;
    }

    public function setType(bool $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getAvailableTime(): ?int
    {
        return $this->AvailableTime;
    }

    public function setAvailableTime(?int $AvailableTime): self
    {
        $this->AvailableTime = $AvailableTime;

        return $this;
    }

    public function getUserMember(): ?User
    {
        return $this->UserMember;
    }

    public function setUserMember(?User $UserMember): self
    {
        $this->UserMember = $UserMember;

        return $this;
    }

    /**
     * @return Collection|Activity[]
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): self
    {
        if (!$this->activities->contains($activity)) {
            $this->activities[] = $activity;
            $activity->addFamilyMemberActivity($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): self
    {
        if ($this->activities->contains($activity)) {
            $this->activities->removeElement($activity);
            $activity->removeFamilyMemberActivity($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Entity\User;
use App\Form\RegisterType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use App\Security\UserAuthenticator;

class SecurityController extends AbstractController
{
    /**
     * @Route("/", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('booking_calendar');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    /**
     * @Route("/register", name="register")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, UserAuthenticator $authenticator): Response
    {
        $user = new User();
        $form = $this->createForm(RegisterType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_login');
            // // do anything else you need here, like send an email

            // return $guardHandler->authenticateUserAndHandleSuccess(
            //     $user,
            //     $request,
            //     $authenticator,
            //     'main' // firewall name in security.yaml
            // );
        }

        return $this->render('security/register.html.twig',[
            'registerform' => $form->createView(),
        ]);
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Log in!{% endblock %}

{% block body %}{{ parent() }}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            Tu es connecté avec {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h2 class="h3 mb-3 font-weight-normal">Connecte toi !</h2>
    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Se souvenir de moi
            </label>
        </div>
   

    <button class="validationButton" type="submit">
        Se connecter
    </button>
</form>
<div class="registerButton">
    <a href="{{ path('register') }}">    
        <button class="addButton">
            Rejoins nous !
        </button>
    </a>

</div>


{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Rejoins Nous !{% endblock %}

{% block body %}{{ parent() }}
{{ form_start(registerform) }}
    <h2>Rejoins nous !</h2>
    <div>
        {{ form_row(registerform.username) }}
    </div>
    <div>
        {{ form_row(registerform.email) }}
    </div>
    <div>
        {{ form_row(registerform.plainPassword) }}
    </div>
    <div>
        {{ form_row(registerform.color) }}
    </div>
    <div>
        {{ form_errors(registerform) }}
        <input class="validationButton" type="submit" value="S'enregistrer"/>
    </div>
    <a href="/">
Déjà inscrit ?
    </a>
{{ form_end(registerform) }}
{% endblock %}